---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-graylog
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd-graylog
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-graylog
roleRef:
  kind: ClusterRole
  name: fluentd-graylog
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd-graylog
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-graylog
  namespace: kube-system
  labels:
    k8s-app: fluentd-graylog
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-graylog
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      securityContext: {}
      serviceAccount: fluentd-graylog
      serviceAccountName: fluentd-graylog
      priorityClassName: cluster-logging
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-graylog
        image: fluent/fluentd-kubernetes-daemonset:v1.4-debian-graylog
        env:
          - name:  FLUENT_FOWARD_HOST
            value: ""
          - name:  FLUENT_FOWARD_PORT
            value: ""
          - name: FLUENT_GRAYLOG_HOST
            value: "graylog-gelf-udp.graylog.svc"
          - name: FLUENT_GRAYLOG_PORT
            value: "12201"
          - name: FLUENT_UID
            value: "0"
          - name: FLUENTD_PROMETHEUS_CONF
            value: "disable"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
